### ISSUE TITLE
Mobile Safari claims page to be not safe

### ISSUE THREAD

**Issue by rhafner** [biotope/website#119]
![mobile_safari_page_not_safe](https://user-images.githubusercontent.com/2380594/66988658-316c9780-f0c3-11e9-9ce3-0f6eb69e6e75.jpeg)
"Nicht sicher" = "not safe"

**Comment by jurekbarth** [comment]
needs a redirect from http to https. For netlify and aws cloudfront it's a setting in the controlpanel.
