### ISSUE TITLE
Update introduction for section "Biotope Installation"

### ISSUE THREAD

**Issue by rhafner** [biotope/website#123]
The current intro ends with an "and"
"... Build up your Web Component Library together and"

This is confusing because it looks like the text is incomplete and got cut of.

Please check whether copy text is missing. If not please remove the "and" and end with a "."
"... Build up your Web Component Library together."

**Comment by IvailoStoyanov** [comment]
As I understood it the "and" is supposed to lead to the installation steps like so :
and.... install Package.... and so on. 

I have removed the "and" and placed a full stop.
