### ISSUE TITLE
Contact links not working

### ISSUE THREAD

**Issue by SheepFromHeaven** [biotope/website#134]
When I press on any of the mailto link, it just opens a new tab with the url and NOT the email programm

**Comment by clemensf** [comment]
I could not reproduce it. Which OS and browser did you test it on?

**Comment by clemensf** [comment]
@IvailoStoyanov can you please check this on monday?

**Comment by rhafner** [comment]
I can reproduce the issue on Windows and iOS but only for the contact buttons:
- Chrome, Edge, IE11 open an outlook mail window as expected
- Firefox and Mobile Safari (iOS 13.1.3)  open a new tab and an outlook mail window
- Mobile Firefox (iOS 13.1.3) does not do anything

Ordinary mailto-links work in all browsers as expected.

Additionally I get a security warning on Mobile Safari for the contact buttons which I don't get for the ordinary mailto-links: "This website has been blocked for the automatic generation of e-mails."

**Comment by clemensf** [comment]
yes, I also got the security warning. 
Should we implement the contact buttons as ordinary links instead of a webComponent?
