### ISSUE TITLE
Add open graph image to head to improve sharing in social media channels

### ISSUE THREAD

**Issue by PepeCortisona** [biotope/website#165]
## Expected behavior
A nice visual is displayed with the shared URL of the site

## Actual behavior
When sharing the URL of the home page in Facebook or Microsoft Teams for instance, no thumbnail is displayed for the link.

## Steps to reproduce

  1. Share link
  2. Look at the shared link

The open graph image property is present in the html head of the page, but it's always empty:
`<meta property="og:image" content="">`

**Comment by rhafner** [comment]
Implemented
