### ISSUE TITLE
Use native elements for navigation

### ISSUE THREAD

**Issue by vascocosta-vi** [biotope/website#166]
## Expected behavior
Anchors are used for navigation on the "Code & Resources", "Tutorials" and "See how" (footer) sections.

## Actual behavior
Buttons are being used for navigation on those sections.

**Comment by rhafner** [comment]
Basically all button-tags that are used to navigate should be changed to anchor-tags.
There are also buttons on the splash screen ("see how it works" + "see docs") and in the intro ("who's behind Biotope")

**Comment by luke-m** [comment]
Can you shortly elaborate why you think that should be done @vascocosta-vi ?

**Comment by vascocosta-vi** [comment]
Yes. Buttons are to send commands to the page (toggles, submit forms, perform actions. Links are for navigation.
It also helps with getting the side indexed by web crawlers.
Lastly, the current code is not working as expected:
![image](https://user-images.githubusercontent.com/42742597/67845068-b9f12c00-faf6-11e9-8c65-974c5ffb2f3a.png)

**Comment by rhafner** [comment]
Implemented
