### ISSUE TITLE
Proposal: Usability improvement to copy code snippets

### ISSUE THREAD

**Issue by rhafner** [biotope/website#168]
## Proposed behavior
When I hover over a code snippet I get a tooltip to indicate that I can click on the code snippet and have it copied to my clipboard.

## Actual behavior
Currently the user needs to select the code and copy it via CTRL+V or context menu.

What do you think? Would this improvement help to make it more convenient or would that rather disrupt the user experience?

**Comment by luke-m** [comment]
I think that's a good idea.

**Comment by rhafner** [comment]
Implemented
