### ISSUE TITLE
Decide on browser support

### ISSUE THREAD

**Issue by rhafner** [biotope/website#2]
What browser do we need to support to what extend?

Use progressive enhancement to give every browser the best experience that it can natively provide without any expensive workarounds. Use polyfills were performance is good enough and more efficient than providing a different solution.

**Comment by jurekbarth** [comment]
I would suggest to go with Support for all major 4 vendors in it's latest version. You could even consider leaving Edge in a first step as they'll switch to Chromium in Q3/2019. 

As a starting point for some data you could have a look at the data [css-tricks](https://css-tricks.com/thank-you-2018-edition/) publishes every year. 

>  ...Edge hasn't actually done that yet and Chrome is already pretty darn dominant already, particularly on this site. 77% of traffic is Chrome, 11% Firefox, 6% Safari, about 1.5% each for IE and Edge, and then the rest sprinkled out through 836 other identified browsers...

**Comment by IvailoStoyanov** [comment]
@luke-m 
Will approach @timomayer for this.
