### ISSUE TITLE
!! To be clarified with CoreGroup and/or Timo:

### ISSUE THREAD

**Issue by clemensf** [biotope/website#72]
To be clarified with CoreGroup and/or Timo:
SplashScreen:
- Biotope with capital "B" or lower case in text vs. Logo?
- If the website will be hosted on biotope.sh, where will the current docs from biotope.sh be hosted ?
- "Read docs": Where should it link to? current docs of biotope.sh: "Quickstart"?

Benefits:
- Who is displayed on "who's behind Biotope"?

Animation:
- @timomayer: Discuss with Timo on reducing subsections from 6 -> 4

WantToKnowMore:
- "Get in touch": Which E-Mail address?

Resources:
- "Read docs": Where should it link to?
- "Contact": Which E-Mail address?
- Where should the links for tutorials lead to?

GoodCompany:
- @Timo: Which clients logos can we display?
- "Contact VI": Which E-Mail address?

Footer:
- Imprint: Where's content coming from? Is it legally okay?
- Privacy Policy: Where's content coming from? Is it legally okay?

**Comment by rhafner** [comment]
Results from our meeting:

SplashScreen:

- Biotope in text paragraphs: with capital "B" or lower case in text (like in the logo)?
-> "Biotope" capitalized in copy text! Replace any occurences of "Bioto.pe" to "Biotope"

- If the website will be hosted on biotope.sh, where will the current docs from biotope.sh be hosted ?
- "Read docs": Where should it link to? current docs of biotope.sh: "Quickstart"?
-> for now: on GitHub.com/biotope/biotope/docs

However this is just some text trying to explain biotope!
Should we rather link to this one?: https://github.com/biotope/biotope/blob/master/docs/quickstart.md 
-> Clemens Fiedler: clarifies this with Timo Mayer.
-> (Finally, when unified docs are ready until go live: docs.biotope.sh OR documentation.biotope.sh)
-> (Timo will clarify if unified docs will be finished until go live)

Benefits:
Who is displayed on "who's behind Biotope"?
-> Core Group: The 4 on the page already.
-> + all Contributors of all biotope repos on GitHub, at least 10 people. Don’t forget ourselves!
-> Internal people first, then decide on the others.

-> TODO @Ralf: Copy out the names and send an E-Mail to all of them with a deadline of 2 days to opt put.

-> Use pictures directly from GitHub, for CoreGroup AND for Collaborators.


Animation:
Reducing subsections from 6 -> 4 ?
-> ask the community in Teams. The more concrete the better! Option A or B.
-> PERFORMANCE! OPTIMIZE SECTION COLLABORATE, reduce elements in SVG -> @Jogi.

WantToKnowMore:
"Get in touch": Which E-Mail address?
-> remove the section WantToKnow completely!

Resources:
"Read docs": Where should it link to?
-> see above.

"Contact": Which E-Mail address?
-> coregroup@biotope.sh

Where should the links for tutorials lead to?
-> Create Web Components with bio elements: Link to Bop Element Documentation: element.biotope.sh/docs/
-> Change „Asynchronously load components …“ to link to the website project on GitHub itself.
-> Automate your build process with Biotope-Build: Build.biotope.sh

GoodCompany:
Which clients logos can we display?
-> see currently online references on virtual.identity.com, we can display these: Roche, UI, Siemens, BASF. 

"Contact VI": Which E-Mail address?
-> link to: info@virtual-identity.com

Footer:
Imprint and Privacy Policy: Where's content coming from? Is it legally okay?
-> Take a default one from own search on the web, eg. Imprint generator: Impressum-recht.de
-> Or look at any client project having an EN imprint / privacy policy
-> Ralf Hafner will do some research.
