### ISSUE TITLE
Responsive Webdesign Issues

### ISSUE THREAD

**Issue by christophsaile** [biotope/website#83]
Hello,

there are some issues with the responsive webdesign of the biotope website on a 13" monitor and mobile.
I have attached some screenshots to show the problems.

1. Text not fully visible
2. Slide gets covered by the bottom line
3. Font not readable
4. Little typo :)  

![responsive](https://user-images.githubusercontent.com/54807480/66377161-4f464800-e9b1-11e9-8ac9-0c0ef57b8e00.PNG)
![responsive 2](https://user-images.githubusercontent.com/54807480/66377165-51100b80-e9b1-11e9-8f56-a37d89ad9181.PNG)
![responsive 3](https://user-images.githubusercontent.com/54807480/66377268-89174e80-e9b1-11e9-89ab-c3e2794d88ad.PNG)
![typo](https://user-images.githubusercontent.com/54807480/66377169-51a8a200-e9b1-11e9-90a6-43a553492b4b.PNG)

**Comment by luke-m** [comment]
Thank you!

**Comment by clemensf** [comment]
Thanks for testing and pointing that out! we fixed the issues this week.
