### ISSUE TITLE
Add tracking

### ISSUE THREAD

**Issue by rhafner** [biotope/website#9]
We want to learn whether our website is helpful and what parts the users engage with to further improve the website.

Coordinate tracking concept, add tracking snippet and extend Biotope components with tracking functionality

Priority of tracking:
- Page Views + Bounce Rate
- Clicks on Links/Buttons
- Scroll to section

**Comment by jurekbarth** [comment]
I would suggest to go with Support for all major 4 vendors in it's latest version. You could even consider leaving Edge in a first step as they'll switch to Chromium in Q3/2019. 

As a starting point for some data you could have a look at the data [css-tricks](https://css-tricks.com/thank-you-2018-edition/) publishes every year. 

>  ...Edge hasn't actually done that yet and Chrome is already pretty darn dominant already, particularly on this site. 77% of traffic is Chrome, 11% Firefox, 6% Safari, about 1.5% each for IE and Edge, and then the rest sprinkled out through 836 other identified browsers...

**Comment by luke-m** [comment]
@jurekbarth wrong thread? #2 is probably where you wanted to post this. 
BTW nice to hear from you :)

**Comment by jurekbarth** [comment]
@luke-m well yes, i've added the same comment in issue #2. Sorry ✌️

**Comment by SheepFromHeaven** [comment]
@biotope/website-project we already have tracking setup with a decorator. So if you need any help... ;)

**Comment by jurekbarth** [comment]
Or you might want to use netlify's build in analytics: https://www.netlify.com/products/analytics/

**Comment by timomayer** [comment]
we need the analytics to work together with our google campaigns, so i think google analytics is the best choice
